#ifndef GBUFFER_DATA_H_INCLUDED
#define GBUFFER_DATA_H_INCLUDED

#define GBUFFER_DATA_PRIMARY                0

#define GBUFFER_DATA_SECONDARY_GI           1
#define GBUFFER_DATA_SECONDARY_REFLECTION   2
#define GBUFFER_DATA_SECONDARY_REFRACTION   3

#define GBUFFER_DATA_TERTIARY_GI            4
#define GBUFFER_DATA_TERTIARY_REFLECTION_GI 5
#define GBUFFER_DATA_TERTIARY_REFRACTION_GI 6

#define GBUFFER_DATA_NUM                    7

#endif