#include "RaytracingBridge.h"

#include "BlueNoise.h"
#include "Bridge.h"
#include "CopyPS.h"
#include "CopyVS.h"
#include "DLSS.h"
#include "EnvironmentColor.h"
#include "File.h"
#include "FSR.h"
#include "Message.h"
#include "Profiler.h"
#include "ShaderLibrary.h"
#include "ShaderMapping.h"
#include "Skinning.h"
#include "Utilities.h"

RaytracingBridge::RaytracingBridge(const Device& device, const std::string& directoryPath)
{
    const INIReader reader("GenerationsRaytracing.ini");

    if (reader.GetInteger("Mod", "Upscaler", 0))
        upscaler = std::make_unique<FSR>(device);
    else 
        upscaler = std::make_unique<DLSS>(device, directoryPath);

    shaderMapping.load(directoryPath + "/ShaderMapping.bin");

    shaderLibrary = device.nvrhi->createShaderLibrary(SHADER_LIBRARY, sizeof(SHADER_LIBRARY));

    size_t shaderLibraryByteSize = 0;
    auto shaderLibraryBytes = readAllBytes(directoryPath + "/ShaderLibrary.cso", shaderLibraryByteSize);

    shaderLibraryAutoGenerated = device.nvrhi->createShaderLibrary(shaderLibraryBytes.get(), shaderLibraryByteSize);

    bindingLayout = device.nvrhi->createBindingLayout(nvrhi::BindingLayoutDesc()
        .setVisibility(nvrhi::ShaderType::AllRayTracing)
        .addItem(nvrhi::BindingLayoutItem::VolatileConstantBuffer(0))
        .addItem(nvrhi::BindingLayoutItem::VolatileConstantBuffer(1))
        .addItem(nvrhi::BindingLayoutItem::VolatileConstantBuffer(2))
        .addItem(nvrhi::BindingLayoutItem::RayTracingAccelStruct(0))

        .addItem(nvrhi::BindingLayoutItem::StructuredBuffer_SRV(1))
        .addItem(nvrhi::BindingLayoutItem::StructuredBuffer_SRV(2))
        .addItem(nvrhi::BindingLayoutItem::StructuredBuffer_SRV(3))

        .addItem(nvrhi::BindingLayoutItem::Texture_UAV(0))
        .addItem(nvrhi::BindingLayoutItem::Texture_UAV(1))
        .addItem(nvrhi::BindingLayoutItem::Texture_UAV(2))
        .addItem(nvrhi::BindingLayoutItem::Texture_UAV(3))
        .addItem(nvrhi::BindingLayoutItem::Texture_UAV(4))
        .addItem(nvrhi::BindingLayoutItem::Texture_UAV(5))
        .addItem(nvrhi::BindingLayoutItem::Texture_UAV(6))
        .addItem(nvrhi::BindingLayoutItem::Texture_UAV(7))
        .addItem(nvrhi::BindingLayoutItem::Texture_UAV(8))
        .addItem(nvrhi::BindingLayoutItem::Texture_UAV(9))
        .addItem(nvrhi::BindingLayoutItem::Texture_UAV(10))
        .addItem(nvrhi::BindingLayoutItem::Texture_UAV(11))

        .addItem(nvrhi::BindingLayoutItem::Texture_SRV(4))
        .addItem(nvrhi::BindingLayoutItem::Texture_SRV(5))
        .addItem(nvrhi::BindingLayoutItem::Texture_SRV(6))
        .addItem(nvrhi::BindingLayoutItem::Texture_SRV(7))

        .addItem(nvrhi::BindingLayoutItem::Sampler(0)));

    bindlessLayout = device.nvrhi->createBindlessLayout(nvrhi::BindlessLayoutDesc()
        .setVisibility(nvrhi::ShaderType::AllRayTracing)
        .setMaxCapacity(65336)
        .addRegisterSpace(nvrhi::BindingLayoutItem::TypedBuffer_SRV(1))
        .addRegisterSpace(nvrhi::BindingLayoutItem::RawBuffer_SRV(2))
        .addRegisterSpace(nvrhi::BindingLayoutItem::Texture_SRV(3))
        .addRegisterSpace(nvrhi::BindingLayoutItem::Texture_SRV(4)));

    descriptorTable = device.nvrhi->createDescriptorTable(bindlessLayout);
    device.nvrhi->resizeDescriptorTable(descriptorTable, 65536, false);

    rtConstantBuffer = device.nvrhi->createBuffer(nvrhi::BufferDesc()
        .setByteSize(sizeof(RTConstants))
        .setIsConstantBuffer(true)
        .setIsVolatile(true)
        .setMaxVersions(1));

    linearRepeatSampler = device.nvrhi->createSampler(nvrhi::SamplerDesc()
        .setAllFilters(true)
        .setAllAddressModes(nvrhi::SamplerAddressMode::Repeat));

    auto pipelineDesc = nvrhi::rt::PipelineDesc()
        .addBindingLayout(bindingLayout)
        .addBindingLayout(bindlessLayout)

        .addShader({ "PrimaryRayGeneration", shaderLibrary->getShader("PrimaryRayGeneration", nvrhi::ShaderType::RayGeneration) })
        .addShader({ "GlobalIlluminationRayGeneration", shaderLibrary->getShader("GlobalIlluminationRayGeneration", nvrhi::ShaderType::RayGeneration) })
        .addShader({ "ShadowRayGeneration", shaderLibrary->getShader("ShadowRayGeneration", nvrhi::ShaderType::RayGeneration) })
        .addShader({ "ReflectionRayGeneration", shaderLibrary->getShader("ReflectionRayGeneration", nvrhi::ShaderType::RayGeneration) })
        .addShader({ "RefractionRayGeneration", shaderLibrary->getShader("RefractionRayGeneration", nvrhi::ShaderType::RayGeneration) })
        .addShader({ "CompositeRayGeneration", shaderLibrary->getShader("CompositeRayGeneration", nvrhi::ShaderType::RayGeneration) })

        .addShader({ "MissPrimary", shaderLibrary->getShader("MissPrimary", nvrhi::ShaderType::Miss) })
        .addShader({ "MissPrimarySky", shaderLibrary->getShader("MissPrimarySky", nvrhi::ShaderType::Miss) })
        .addShader({ "MissSecondary", shaderLibrary->getShader("MissSecondary", nvrhi::ShaderType::Miss) })
        .addShader({ "MissSecondarySky", shaderLibrary->getShader("MissSecondarySky", nvrhi::ShaderType::Miss) })

        .setMaxRecursionDepth(4)
        .setMaxPayloadSize(24);

    for (auto& shader : shaderMapping.shaders)
    {
        const auto primaryClosestHit = shaderLibraryAutoGenerated->getShader(shader.primaryClosestHit.c_str(), nvrhi::ShaderType::ClosestHit);
        const auto secondaryClosestHit = shaderLibraryAutoGenerated->getShader(shader.secondaryClosestHit.c_str(), nvrhi::ShaderType::ClosestHit);
        const auto anyHit = shaderLibraryAutoGenerated->getShader(shader.anyHit.c_str(), nvrhi::ShaderType::AnyHit);
        const auto callable = shaderLibraryAutoGenerated->getShader(shader.callable.c_str(), nvrhi::ShaderType::Callable);

        pipelineDesc.addHitGroup({ shader.primaryClosestHit, primaryClosestHit, anyHit });
        pipelineDesc.addHitGroup({ shader.secondaryClosestHit, secondaryClosestHit, anyHit });
        pipelineDesc.addShader({ shader.callable, callable });
    }

    pipeline = device.nvrhi->createRayTracingPipeline(pipelineDesc);

    shaderTable = pipeline->createShaderTable();

    for (auto& shader : shaderMapping.shaders)
        shaderTable->addCallableShader(shader.callable.c_str());

    skinningShader = device.nvrhi->createShader(nvrhi::ShaderDesc(nvrhi::ShaderType::Compute), SKINNING, sizeof(SKINNING));

    skinningBindingLayout = device.nvrhi->createBindingLayout(nvrhi::BindingLayoutDesc()
        .setVisibility(nvrhi::ShaderType::Compute)
        .addItem(nvrhi::BindingLayoutItem::VolatileConstantBuffer(0))
        .addItem(nvrhi::BindingLayoutItem::RawBuffer_SRV(0))
        .addItem(nvrhi::BindingLayoutItem::TypedBuffer_SRV(1))
        .addItem(nvrhi::BindingLayoutItem::StructuredBuffer_SRV(2))
        .addItem(nvrhi::BindingLayoutItem::RawBuffer_UAV(0)));

    skinningConstantBuffer = device.nvrhi->createBuffer(nvrhi::BufferDesc()
        .setByteSize(sizeof(BottomLevelAS::Geometry::GPU))
        .setIsConstantBuffer(true)
        .setIsVolatile(true)
        .setMaxVersions(1));

    skinningPipeline = device.nvrhi->createComputePipeline(nvrhi::ComputePipelineDesc()
        .setComputeShader(skinningShader)
        .addBindingLayout(skinningBindingLayout));

    pointClampSampler = device.nvrhi->createSampler(nvrhi::SamplerDesc()
        .setAllFilters(false)
        .setAllAddressModes(nvrhi::SamplerAddressMode::Clamp));

    copyBindingLayout = device.nvrhi->createBindingLayout(nvrhi::BindingLayoutDesc()
        .setVisibility(nvrhi::ShaderType::Pixel)
        .addItem(nvrhi::BindingLayoutItem::Texture_SRV(0))
        .addItem(nvrhi::BindingLayoutItem::Texture_SRV(1))
        .addItem(nvrhi::BindingLayoutItem::Sampler(0)));

    copyVertexShader = device.nvrhi->createShader(nvrhi::ShaderDesc(nvrhi::ShaderType::Vertex), COPY_VS, sizeof(COPY_VS));
    copyPixelShader = device.nvrhi->createShader(nvrhi::ShaderDesc(nvrhi::ShaderType::Pixel), COPY_PS, sizeof(COPY_PS));

    copyDrawArguments.setVertexCount(6);
}

RaytracingBridge::~RaytracingBridge() = default;

void RaytracingBridge::procMsgCreateGeometry(Bridge& bridge)
{
    const auto msg = bridge.msgReceiver.getMsgAndMoveNext<MsgCreateGeometry>();
    const void* data = bridge.msgReceiver.getDataAndMoveNext(msg->nodeNum);

    auto& blas = bottomLevelAccelStructs[msg->bottomLevelAS];
    auto& blasInstance = blas.instances[msg->instanceInfo];

    auto& geometryDesc =
        blasInstance.desc.bottomLevelGeometries.size() > blasInstance.curGeometryIndex ?
        blasInstance.desc.bottomLevelGeometries[blasInstance.curGeometryIndex] :
        blasInstance.desc.bottomLevelGeometries.emplace_back();

    if (msg->opaque)
        geometryDesc.flags = nvrhi::rt::GeometryFlags::Opaque;

    auto& triangles = geometryDesc.geometryData.triangles;

    triangles.indexBuffer = nvrhi::checked_cast<nvrhi::IBuffer*>(bridge.resources[msg->indexBuffer].Get());
    triangles.vertexBuffer = nvrhi::checked_cast<nvrhi::IBuffer*>(bridge.resources[msg->vertexBuffer].Get());

    assert(triangles.indexBuffer && triangles.vertexBuffer);

    triangles.indexFormat = nvrhi::Format::R16_UINT;
    triangles.vertexFormat = nvrhi::Format::RGB32_FLOAT;
    triangles.indexOffset = msg->indexOffset;
    triangles.vertexOffset = msg->vertexOffset;
    triangles.indexCount = msg->indexCount;
    triangles.vertexCount = msg->vertexCount;
    triangles.vertexStride = msg->vertexStride;

    auto& geometry =
        blasInstance.geometries.size() > blasInstance.curGeometryIndex ?
        blasInstance.geometries[blasInstance.curGeometryIndex] :
        blasInstance.geometries.emplace_back(descriptorTableManager);

    if (geometry.vertexBuffer != triangles.vertexBuffer ||
        geometry.indexBuffer != triangles.indexBuffer)
    {
        geometry.skinningBuffer = nullptr;
        geometry.prevSkinningBuffer = nullptr;
        geometry.releaseDescriptors();

        blasInstance.handle = nullptr;
    }

    geometry.gpu.vertexBuffer = msg->vertexBuffer;
    geometry.gpu.prevVertexBuffer = msg->vertexBuffer;

    geometry.gpu.vertexCount = msg->vertexCount;
    geometry.gpu.vertexStride = msg->vertexStride;
    geometry.gpu.normalOffset = msg->normalOffset;
    geometry.gpu.tangentOffset = msg->tangentOffset;
    geometry.gpu.binormalOffset = msg->binormalOffset;
    geometry.gpu.texCoordOffset = msg->texCoordOffset;
    geometry.gpu.colorOffset = msg->colorOffset;
    geometry.gpu.colorFormat = msg->colorFormat;
    geometry.gpu.blendWeightOffset = msg->blendWeightOffset;
    geometry.gpu.blendIndicesOffset = msg->blendIndicesOffset;

    geometry.gpu.indexBuffer = msg->indexBuffer;

    geometry.gpu.material = msg->material;
    geometry.gpu.punchThrough = msg->punchThrough;

    geometry.vertexBuffer = triangles.vertexBuffer;
    geometry.indexBuffer = triangles.indexBuffer;

    if (msg->instanceInfo != 0)
    {
        geometry.skinningBufferId = GEOMETRY_SKINNING_BUFFER_ID(msg->vertexBuffer, msg->instanceInfo);
        geometry.prevSkinningBufferId = GEOMETRY_PREV_SKINNING_BUFFER_ID(msg->vertexBuffer, msg->instanceInfo);
    }

    if (msg->nodeNum > 0)
    {
        auto& nodeIndicesBuffer = blas.nodeIndicesBuffers[XXH64(data, msg->nodeNum, 0)];
        if (!nodeIndicesBuffer)
        {
            nodeIndicesBuffer = bridge.device.nvrhi->createBuffer(nvrhi::BufferDesc()
                .setByteSize(msg->nodeNum)
                .setFormat(nvrhi::Format::R8_UINT)
                .setCanHaveTypedViews(true)
                .setInitialState(nvrhi::ResourceStates::CopyDest)
                .setKeepInitialState(true));

            bridge.openCommandListForCopy();
            bridge.commandListForCopy->writeBuffer(nodeIndicesBuffer, data, msg->nodeNum);
            bridge.commandList->setPermanentBufferState(nodeIndicesBuffer, nvrhi::ResourceStates::ShaderResource);
        }

        geometry.nodeIndicesBuffer = nodeIndicesBuffer;
    }
    else
    {
        geometry.nodeIndicesBuffer = nullptr;
    }

    blasInstance.curGeometryIndex += 1;
}

void RaytracingBridge::procMsgCreateBottomLevelAS(Bridge& bridge)
{
    const auto msg = bridge.msgReceiver.getMsgAndMoveNext<MsgCreateBottomLevelAS>();

    const size_t matrixByteSize = msg->matrixNum * 64;
    const void* data = bridge.msgReceiver.getDataAndMoveNext(matrixByteSize);

    const auto blasPair = bottomLevelAccelStructs.find(msg->bottomLevelAS);
    if (blasPair == bottomLevelAccelStructs.end())
        return;

    const auto instancePair = blasPair->second.instances.find(msg->instanceInfo);
    if (instancePair == blasPair->second.instances.end())
        return;

    if (msg->matrixNum > 0)
    {
        if (instancePair->second.matrixBuffer == nullptr ||
            instancePair->second.matrixBuffer->getDesc().byteSize != matrixByteSize)
        {
            instancePair->second.matrixBuffer = bridge.device.nvrhi->createBuffer(nvrhi::BufferDesc()
                .setByteSize(matrixByteSize)
                .setStructStride(64)
                .setCpuAccess(nvrhi::CpuAccessMode::Write));

            instancePair->second.matrixHash = 0;
        }

        const XXH64_hash_t matrixHash = XXH64(data, matrixByteSize, 0);
        if (matrixHash != instancePair->second.matrixHash)
        {
            void* memory = bridge.device.nvrhi->mapBuffer(instancePair->second.matrixBuffer, nvrhi::CpuAccessMode::Write);
            memcpy(memory, data, matrixByteSize);
            bridge.device.nvrhi->unmapBuffer(instancePair->second.matrixBuffer);

            instancePair->second.handle = nullptr;
            instancePair->second.matrixHash = matrixHash;
        }
    }

    instancePair->second.desc.bottomLevelGeometries.resize(instancePair->second.curGeometryIndex);
    instancePair->second.geometries.resize(instancePair->second.curGeometryIndex, { descriptorTableManager });
    instancePair->second.curGeometryIndex = 0;
}

void RaytracingBridge::procMsgCreateInstance(Bridge& bridge)
{
    const auto msg = bridge.msgReceiver.getMsgAndMoveNext<MsgCreateInstance>();

    auto& instance = instances.emplace_back();
    memcpy(instance.transform, msg->transform, sizeof(instance.transform));
    memcpy(instance.gpu.prevTransform, msg->prevTransform, sizeof(instance.gpu.prevTransform));
    instance.bottomLevelAS = msg->bottomLevelAS;
    instance.instanceInfo = msg->instanceInfo;
    instance.instanceMask = msg->instanceMask;
}

void RaytracingBridge::procMsgCreateMaterial(Bridge& bridge)
{
    const auto msg = bridge.msgReceiver.getMsgAndMoveNext<MsgCreateMaterial>();

    auto& material = materials[msg->material];

    const auto pair = shaderMapping.indices.find(msg->shader);

    if (pair != shaderMapping.indices.end())
        material.shader = pair->second;
    else
        material.shader = shaderMapping.indices["SysError"];

    memcpy(material.gpu.textures, msg->textures, sizeof(msg->textures));
    memcpy(material.gpu.parameters, msg->parameters, sizeof(msg->parameters));
}

void RaytracingBridge::procMsgReleaseInstanceInfo(Bridge& bridge)
{
    const auto msg = bridge.msgReceiver.getMsgAndMoveNext<MsgReleaseInstanceInfo>();
    pendingReleases.emplace_back(msg->bottomLevelAS, msg->instanceInfo);
}

template<typename T>
static void createUploadBuffer(const Bridge& bridge, const std::vector<T>& vector, nvrhi::BufferHandle& buffer)
{
    buffer = bridge.device.nvrhi->createBuffer(nvrhi::BufferDesc()
        .setByteSize(vectorByteSize(vector))
        .setStructStride((uint32_t)vectorByteStride(vector))
        .setCpuAccess(nvrhi::CpuAccessMode::Write));

    void* copyDest = bridge.device.nvrhi->mapBuffer(buffer, nvrhi::CpuAccessMode::Write);
    memcpy(copyDest, vector.data(), vectorByteSize(vector));
    bridge.device.nvrhi->unmapBuffer(buffer);
}

void RaytracingBridge::procMsgNotifySceneTraversed(Bridge& bridge)
{
    const auto msg = bridge.msgReceiver.getMsgAndMoveNext<MsgNotifySceneTraversed>();

    if (instances.empty())
        return;

    auto& colorAttachment = bridge.framebufferDesc.colorAttachments[0].texture;
    if (!colorAttachment || colorAttachment->getDesc().format != nvrhi::Format::RGBA16_FLOAT)
        return;

    PUSH_PROFILER("Create GPU Materials");

    bindingSetItems.clear();
    materialBufferVec.clear();

    for (auto& [id, material] : materials)
    {
        material.indexInBuffer = (uint32_t)materialBufferVec.size();
        auto& gpuMaterial = materialBufferVec.emplace_back();

        for (size_t i = 0; i < 16; i++)
        {
            if (!material.gpu.textures[i])
                continue;

            const auto texPair = bridge.resources.find(material.gpu.textures[i]);
            if (texPair == bridge.resources.end() || !descriptorTableManager.put(material.gpu.textures[i], gpuMaterial.textures[i]))
                continue;

            bindingSetItems.push_back(nvrhi::BindingSetItem::Texture_SRV(gpuMaterial.textures[i], 
                nvrhi::checked_cast<nvrhi::ITexture*>(texPair->second.Get())));
        }

        memcpy(gpuMaterial.parameters, material.gpu.parameters, sizeof(material.gpu.parameters));
    }

    POP_PROFILER();
    PUSH_PROFILER("Create Shader Table and GPU Geometries");

    const bool hasEnvironmentColor = EnvironmentColor::get(bridge, rtConstants.environmentColor);

    shaderTable->clearMissShaders();
    shaderTable->addMissShader("MissPrimary"); // MISS
    shaderTable->addMissShader("MissPrimarySky"); // MISS_SKY
    shaderTable->addMissShader(hasEnvironmentColor ? "MissSecondary" : "MissSecondarySky"); // MISS_GLOBAL_ILLUMINATION
    shaderTable->addMissShader("MissSecondary"); // MISS_SHADOW
    shaderTable->addMissShader("MissSecondarySky"); // MISS_REFLECTION_REFRACTION

    geometryBufferVec.clear();
    shaderTable->clearHitShaders();

    for (auto& [id, blas] : bottomLevelAccelStructs)
    {
        for (auto it = blas.instances.begin(); it != blas.instances.end();)
        {
            if (it->second.geometries.empty())
            {
                it = blas.instances.erase(it);
                continue;
            }

            it->second.indexInBuffer = (uint32_t)geometryBufferVec.size();

            for (size_t i = 0; i < it->second.geometries.size(); i++)
            {
                auto& geometry = it->second.geometries[i];
                const auto pair = materials.find(geometry.gpu.material);
                auto& gpuGeometry = geometryBufferVec.emplace_back(geometry.gpu);

                if (pair != materials.end())
                {
                    const auto& shader = shaderMapping.shaders[pair->second.shader];

                    shaderTable->addHitGroup(shader.primaryClosestHit.c_str());
                    shaderTable->addHitGroup(shader.secondaryClosestHit.c_str());

                    gpuGeometry.material = pair->second.indexInBuffer;
                }
                else
                {
                    shaderTable->addHitGroup("SysError_primary_closesthit");
                    shaderTable->addHitGroup("SysError_secondary_closesthit");

                    gpuGeometry.material = NULL;
                }

                if (it->second.handle == nullptr && geometry.nodeIndicesBuffer != nullptr)
                {
                    std::swap(geometry.skinningBuffer, geometry.prevSkinningBuffer);
                    std::swap(geometry.skinningBufferId, geometry.prevSkinningBufferId);

                    if (geometry.skinningBuffer == nullptr)
                    {
                        auto desc = geometry.vertexBuffer->getDesc();
                        geometry.skinningBuffer = bridge.device.nvrhi->createBuffer(desc.setCanHaveUAVs(true));
                    }

                    bridge.commandList->writeBuffer(skinningConstantBuffer, &geometry.gpu, sizeof(BottomLevelAS::Geometry::GPU));

                    auto skinningBindingSet = bridge.device.nvrhi->createBindingSet(nvrhi::BindingSetDesc()
                        .addItem(nvrhi::BindingSetItem::ConstantBuffer(0, skinningConstantBuffer))
                        .addItem(nvrhi::BindingSetItem::RawBuffer_SRV(0, geometry.vertexBuffer))
                        .addItem(nvrhi::BindingSetItem::TypedBuffer_SRV(1, geometry.nodeIndicesBuffer))
                        .addItem(nvrhi::BindingSetItem::StructuredBuffer_SRV(2, it->second.matrixBuffer))
                        .addItem(nvrhi::BindingSetItem::RawBuffer_UAV(0, geometry.skinningBuffer)), skinningBindingLayout);

                    bridge.commandList->setComputeState(nvrhi::ComputeState()
                        .setPipeline(skinningPipeline)
                        .addBindingSet(skinningBindingSet));

                    bridge.commandList->dispatch((geometry.gpu.vertexCount + 63) / 64);

                    it->second.desc.bottomLevelGeometries[i].geometryData.triangles.vertexBuffer = geometry.skinningBuffer;
                }

                if (descriptorTableManager.put(geometry.gpu.indexBuffer, gpuGeometry.indexBuffer))
                    bindingSetItems.push_back(nvrhi::BindingSetItem::TypedBuffer_SRV(gpuGeometry.indexBuffer, geometry.indexBuffer));

                if (geometry.skinningBuffer != nullptr)
                {
                    if (descriptorTableManager.put(geometry.skinningBufferId, gpuGeometry.vertexBuffer))
                        bindingSetItems.push_back(nvrhi::BindingSetItem::RawBuffer_SRV(gpuGeometry.vertexBuffer, geometry.skinningBuffer));

                    if (geometry.prevSkinningBuffer != nullptr)
                    {
                        if (descriptorTableManager.put(geometry.prevSkinningBufferId, gpuGeometry.prevVertexBuffer))
                            bindingSetItems.push_back(nvrhi::BindingSetItem::RawBuffer_SRV(gpuGeometry.prevVertexBuffer, geometry.prevSkinningBuffer));
                    }
                    else
                    {
                        gpuGeometry.prevVertexBuffer = gpuGeometry.vertexBuffer;
                    }
                }
                else
                {
                    if (descriptorTableManager.put(geometry.gpu.vertexBuffer, gpuGeometry.vertexBuffer))
                        bindingSetItems.push_back(nvrhi::BindingSetItem::RawBuffer_SRV(gpuGeometry.vertexBuffer, geometry.vertexBuffer));

                    gpuGeometry.prevVertexBuffer = gpuGeometry.vertexBuffer;
                }
            }

            if (it->second.handle == nullptr)
            {
                it->second.handle = bridge.device.nvrhi->createAccelStruct(it->second.desc
                    .setBuildFlags(it->second.matrixBuffer != nullptr ? nvrhi::rt::AccelStructBuildFlags::PreferFastBuild : nvrhi::rt::AccelStructBuildFlags::PreferFastTrace));

                nvrhi::utils::BuildBottomLevelAccelStruct(bridge.commandList, it->second.handle, it->second.desc);
            }

            ++it;
        }
    }

    POP_PROFILER();
    PUSH_PROFILER("Write Descriptor Table");

    const uint32_t descriptorTableCapacity = nextPowerOfTwo(descriptorTableManager.getCapacity());

    if (descriptorTable->getCapacity() < descriptorTableCapacity)
        bridge.device.nvrhi->resizeDescriptorTable(descriptorTable, descriptorTableCapacity);

    for (auto& bindingSetItem : bindingSetItems)
        bridge.device.nvrhi->writeDescriptorTable(descriptorTable, bindingSetItem);

    POP_PROFILER();
    PUSH_PROFILER("Create GPU Instances");

    instanceDescs.clear();
    instanceBufferVec.clear();

    for (auto& instance : instances)
    {
        const auto blasPair = bottomLevelAccelStructs.find(instance.bottomLevelAS);
        if (blasPair == bottomLevelAccelStructs.end())
            continue;

        const auto instancePair = blasPair->second.instances.find(instance.instanceInfo);
        if (instancePair == blasPair->second.instances.end())
            continue;

        auto& desc = instanceDescs.emplace_back();

        memcpy(desc.transform, instance.transform, sizeof(desc.transform));
        instanceBufferVec.push_back(instance.gpu);

        desc.instanceID = instancePair->second.indexInBuffer;
        desc.instanceMask = instance.instanceMask;
        desc.instanceContributionToHitGroupIndex = instancePair->second.indexInBuffer * 2;
        desc.bottomLevelAS = instancePair->second.handle;
    }

    POP_PROFILER();

    if (instanceDescs.empty())
        return;

    PUSH_PROFILER("Build Top Level Acceleration Structure");

    auto topLevelAccelStruct = bridge.device.nvrhi->createAccelStruct(nvrhi::rt::AccelStructDesc()
        .setIsTopLevel(true)
        .setTrackLiveness(true)
        .setTopLevelMaxInstances(instanceDescs.size()));

    bridge.commandList->buildTopLevelAccelStruct(topLevelAccelStruct, instanceDescs.data(), instanceDescs.size());

    POP_PROFILER();

    if (!output)
    {
        auto textureDesc = colorAttachment->getDesc();
        output = bridge.device.nvrhi->createTexture(textureDesc
            .setFormat(nvrhi::Format::RGBA16_FLOAT)
            .setIsRenderTarget(false)
            .setInitialState(nvrhi::ResourceStates::UnorderedAccess)
            .setUseClearValue(false)
            .setIsUAV(true));

        upscaler->validate({ bridge, output });
    }

    PUSH_PROFILER("Create Binding Set");

    bridge.vsConstants.writeBuffer(bridge.commandList, bridge.vsConstantBuffer);
    bridge.psConstants.writeBuffer(bridge.commandList, bridge.psConstantBuffer);

    upscaler->getJitterOffset(rtConstants.currentFrame, rtConstants.jitterX, rtConstants.jitterY);

    bridge.commandList->writeBuffer(rtConstantBuffer, &rtConstants, sizeof(rtConstants));

    memcpy(rtConstants.prevProj, bridge.vsConstants.c[0], sizeof(rtConstants.prevProj));
    memcpy(rtConstants.prevView, bridge.vsConstants.c[4], sizeof(rtConstants.prevView));

    createUploadBuffer(bridge, geometryBufferVec, geometryBuffer);
    createUploadBuffer(bridge, materialBufferVec, materialBuffer);
    createUploadBuffer(bridge, instanceBufferVec, instanceBuffer);

    if (!blueNoise)
    {
        std::unique_ptr<uint8_t[]> ddsData;
        std::vector<D3D12_SUBRESOURCE_DATA> subResources;

        const HRESULT result = DirectX::LoadDDSTextureFromMemory(
            bridge.device.nvrhi, 
            BLUE_NOISE, 
            BLUE_NOISE_SIZE, 
            std::addressof(blueNoise),
            subResources);

        assert(result == S_OK);

        bridge.openCommandListForCopy();
        bridge.commandListForCopy->writeTexture(blueNoise, 0, 0, subResources[0].pData, subResources[0].RowPitch, subResources[0].SlicePitch);
    }

    auto bindingSet = bridge.device.nvrhi->createBindingSet(nvrhi::BindingSetDesc()
        .addItem(nvrhi::BindingSetItem::ConstantBuffer(0, bridge.vsConstantBuffer))
        .addItem(nvrhi::BindingSetItem::ConstantBuffer(1, bridge.psConstantBuffer))
        .addItem(nvrhi::BindingSetItem::ConstantBuffer(2, rtConstantBuffer))

        .addItem(nvrhi::BindingSetItem::RayTracingAccelStruct(0, topLevelAccelStruct))
        .addItem(nvrhi::BindingSetItem::StructuredBuffer_SRV(1, materialBuffer))
        .addItem(nvrhi::BindingSetItem::StructuredBuffer_SRV(2, geometryBuffer))
        .addItem(nvrhi::BindingSetItem::StructuredBuffer_SRV(3, instanceBuffer))

        .addItem(nvrhi::BindingSetItem::Texture_UAV(0, upscaler->position))
        .addItem(nvrhi::BindingSetItem::Texture_UAV(1, upscaler->depth.getCurrent(rtConstants.currentFrame)))
        .addItem(nvrhi::BindingSetItem::Texture_UAV(2, upscaler->motionVector))
        .addItem(nvrhi::BindingSetItem::Texture_UAV(3, upscaler->normal.getCurrent(rtConstants.currentFrame)))
        .addItem(nvrhi::BindingSetItem::Texture_UAV(4, upscaler->texCoord))
        .addItem(nvrhi::BindingSetItem::Texture_UAV(5, upscaler->color))
        .addItem(nvrhi::BindingSetItem::Texture_UAV(6, upscaler->shader))
        .addItem(nvrhi::BindingSetItem::Texture_UAV(7, upscaler->globalIllumination.getCurrent(rtConstants.currentFrame)))
        .addItem(nvrhi::BindingSetItem::Texture_UAV(8, upscaler->shadow))
        .addItem(nvrhi::BindingSetItem::Texture_UAV(9, upscaler->reflection))
        .addItem(nvrhi::BindingSetItem::Texture_UAV(10, upscaler->refraction))
        .addItem(nvrhi::BindingSetItem::Texture_UAV(11, upscaler->composite))

        .addItem(nvrhi::BindingSetItem::Texture_SRV(4, blueNoise))
        .addItem(nvrhi::BindingSetItem::Texture_SRV(5, upscaler->depth.getPrevious(rtConstants.currentFrame)))
        .addItem(nvrhi::BindingSetItem::Texture_SRV(6, upscaler->normal.getPrevious(rtConstants.currentFrame)))
        .addItem(nvrhi::BindingSetItem::Texture_SRV(7, upscaler->globalIllumination.getPrevious(rtConstants.currentFrame)))

        .addItem(nvrhi::BindingSetItem::Sampler(0, linearRepeatSampler)), bindingLayout);

    POP_PROFILER();
    PUSH_PROFILER("Dispatch Rays");

    auto raytracingState = nvrhi::rt::State()
        .setShaderTable(shaderTable)
        .addBindingSet(bindingSet)
        .addBindingSet(descriptorTable);

    auto dispatchRaysArgs = nvrhi::rt::DispatchRaysArguments()
        .setWidth(upscaler->width)
        .setHeight(upscaler->height);

    auto dispatchRays = [&](const char* rayGenerationShader)
    {
        shaderTable->setRayGenerationShader(rayGenerationShader);
        bridge.commandList->setRayTracingState(raytracingState);
        bridge.commandList->dispatchRays(dispatchRaysArgs);
    };

    bridge.commandList->clearTextureFloat(upscaler->depth.getCurrent(rtConstants.currentFrame), nvrhi::TextureSubresourceSet(), nvrhi::Color(1));
    bridge.commandList->clearTextureFloat(upscaler->motionVector, nvrhi::TextureSubresourceSet(), nvrhi::Color(0));
    bridge.commandList->clearTextureUInt(upscaler->shader, nvrhi::TextureSubresourceSet(), 0);
    bridge.commandList->clearTextureFloat(upscaler->composite, nvrhi::TextureSubresourceSet(), nvrhi::Color(1));

    if (msg->resetAccumulation != 0)
        bridge.commandList->clearTextureFloat(upscaler->globalIllumination.getPrevious(rtConstants.currentFrame), nvrhi::TextureSubresourceSet(), nvrhi::Color(0));

    bridge.commandList->setTextureState(upscaler->depth.getCurrent(rtConstants.currentFrame), nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);
    bridge.commandList->setTextureState(upscaler->motionVector, nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);
    bridge.commandList->setTextureState(upscaler->shader, nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);

    dispatchRays("PrimaryRayGeneration");

    bridge.commandList->setTextureState(upscaler->position, nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);
    bridge.commandList->setTextureState(upscaler->depth.getCurrent(rtConstants.currentFrame), nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);
    bridge.commandList->setTextureState(upscaler->motionVector, nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);
    bridge.commandList->setTextureState(upscaler->normal.getCurrent(rtConstants.currentFrame), nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);
    bridge.commandList->setTextureState(upscaler->texCoord, nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);
    bridge.commandList->setTextureState(upscaler->color, nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);
    bridge.commandList->setTextureState(upscaler->shader, nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);

    dispatchRays("GlobalIlluminationRayGeneration");
    dispatchRays("ShadowRayGeneration");
    dispatchRays("ReflectionRayGeneration");
    dispatchRays("RefractionRayGeneration");

    bridge.commandList->setTextureState(upscaler->globalIllumination.getCurrent(rtConstants.currentFrame), nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);
    bridge.commandList->setTextureState(upscaler->shadow, nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);
    bridge.commandList->setTextureState(upscaler->reflection, nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);
    bridge.commandList->setTextureState(upscaler->reflection, nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);
    bridge.commandList->setTextureState(upscaler->composite, nvrhi::TextureSubresourceSet(), nvrhi::ResourceStates::UnorderedAccess);

    dispatchRays("CompositeRayGeneration");

    POP_PROFILER();
    PUSH_PROFILER("Copy Raytracing Composite");

    if (!copyPipeline)
    {
        copyFramebuffer = bridge.device.nvrhi->createFramebuffer(bridge.framebufferDesc);

        copyPipeline = bridge.device.nvrhi->createGraphicsPipeline(nvrhi::GraphicsPipelineDesc()
            .setVertexShader(copyVertexShader)
            .setPixelShader(copyPixelShader)
            .setPrimType(nvrhi::PrimitiveType::TriangleList)
            .setRenderState(nvrhi::RenderState()
                .setDepthStencilState(nvrhi::DepthStencilState()
                    .enableDepthTest()
                    .enableDepthWrite()
                    .setDepthFunc(nvrhi::ComparisonFunc::Always)
                    .disableStencil())
                .setRasterState(nvrhi::RasterState()
                    .setCullNone()))
            .addBindingLayout(copyBindingLayout), copyFramebuffer);
    }

    upscaler->evaluate({ bridge, (size_t)rtConstants.currentFrame, rtConstants.jitterX, rtConstants.jitterY, msg->resetAccumulation ? true : false });

    auto copyBindingSet = bridge.device.nvrhi->createBindingSet(nvrhi::BindingSetDesc()
        .addItem(nvrhi::BindingSetItem::Texture_SRV(0, output))
        .addItem(nvrhi::BindingSetItem::Texture_SRV(1, upscaler->depth.getCurrent(rtConstants.currentFrame)))
        .addItem(nvrhi::BindingSetItem::Sampler(0, pointClampSampler)), copyBindingLayout);;

    bridge.commandList->setGraphicsState(nvrhi::GraphicsState()
        .setPipeline(copyPipeline)
        .addBindingSet(copyBindingSet)
        .setFramebuffer(copyFramebuffer)
        .setViewport(nvrhi::ViewportState()
            .addViewportAndScissorRect(nvrhi::Viewport(
                (float)output->getDesc().width,
                (float)output->getDesc().height))));

    bridge.commandList->draw(copyDrawArguments);

    rtConstants.currentFrame += 1;
    instances.clear();

    POP_PROFILER();
}