{ "bde", "Direct01", "bde_sky_0", { "Stage/bde", "Stage/Common/cmn000" } },
{ "blb", "blb_sky", "blb_sky_000", { "Stage/blb" } },
{ "bne", "bne_Direct01", "bne_sky01", { "Stage/bne" } },
{ "bpc", "bpc_Direct00", "bpc300_sky", { "Stage/bpc" } },
{ "cpz100", "cpz_Direct01", "cpz_sky0", { "Stage/cpz100", "Stage/Common/cmn001", "Stage/Common/cmn002", "Stage/Common/cmn003" } },
{ "cpz200", "cpz_Direct01", "cpz_sky1", { "Stage/Common/cmn001", "Stage/Common/cmn002", "Stage/cpz200" } },
{ "cte100", "CTE_Direct01", "cte_sky_000", { "Stage/cte100", "Stage/Common/cmn004" } },
{ "cte102", "CTE_Direct01", "cte_sky_000", { "Stage/cte102" } },
{ "cte200", "CTE_Direct01", "cte_sky_000", { "Stage/Common/cmn004", "Stage/cte200" } },
{ "ghz100", "Direct01", "ghz_sky_000", { "Stage/ghz100", "Stage/Common/cmn005" } },
{ "ghz103", "ghz103_Direct01", "ghz103_sky_000", { "Stage/ghz103", "Stage/Common/cmn006" } },
{ "ghz104", "ghz104_Direct01", "ghz_sea_sky_night", { "Stage/ghz104" } },
{ "ghz200", "ghz200_Direct01", "ghz_sky_000", { "Stage/Common/cmn005", "Stage/ghz200" } },
{ "sph100", "sph100_Direct01", "sph100_sky00", { "Stage/sph100", "Stage/Common/cmn007" } },
{ "sph101", "sph100_Direct01", "sph_sky_sph101", { "Stage/Common/cmn006", "Stage/sph101" } },
{ "sph200", "sph03_Direct01", "sph200_sky01", { "Stage/Common/cmn007", "Stage/sph200" } },
{ "ssz100", "ssz100_Direct01", "ssz_sky_000", { "Stage/ssz100", "Stage/Common/cmn008" } },
{ "ssz103", "ssz103_Direct01", "ssz103_sky", { "Stage/ssz103" } },
{ "ssz200", "ssz200_Direct01", "ssz_sky_000", { "Stage/Common/cmn008", "Stage/ssz200" } },
{ "bms", "bms_Direct01", "bms_sky", { "Stage/Common/cmn002", "Stage/Common/cmn003", "Stage/bms" } },
{ "bsd", "Direct01", "bsd_sky0", { "Stage/Common/cmn000", "Stage/bsd" } },
{ "bsl", "bsl_Direct00", "bsl_sky", { "Stage/bsl", "Stage/Common/cmn009" } },
{ "cnz100", "cnz_Direct00", "cnz100_sky", { "Stage/cnz100" } },
{ "csc100", "csc_Direct00", "csc100_sky", { "Stage/Common/cmn009", "Stage/csc100" } },
{ "csc200", "csc_Direct00", "csc200_sky", { "Stage/Common/cmn009", "Stage/csc200" } },
{ "euc100", "euc100_Direct01", "euc_sky_000", { "Stage/euc100", "Stage/Common/cmn010", "Stage/Common/cmn011", "Stage/Common/cmn012" } },
{ "euc200", "euc200_Direct01", "euc_sky_000", { "Stage/Common/cmn010", "Stage/Common/cmn011", "Stage/Common/cmn012", "Stage/euc200" } },
{ "euc204", "euc204_Direct01", "euc_sky_evening", { "Stage/euc204", "Stage/Common/cmn013" } },
{ "fig000", "fig000_Direct01", "fig_sky_000", { "Stage/fig000" } },
{ "pam000", "pam000_Direct01", "pam_sky_000", { "Stage/pam000" } },
{ "pla100", "pla100_Direct01", "pla_sky", { "Stage/pla100", "Stage/Common/cmn014", "Stage/Common/cmn015" } },
{ "pla200", "pla200_Direct01", "pla_sky", { "Stage/Common/cmn014", "Stage/Common/cmn015", "Stage/pla200", "Stage/Common/cmn016" } },
{ "pla204", "pla200_Direct01", "pla204_sky", { "Stage/Common/cmn015", "Stage/pla204" } },
{ "pla205", "pla200_Direct01", "pla_sky", { "Stage/Common/cmn014", "Stage/Common/cmn015", "Stage/Common/cmn016", "Stage/pla205" } },
{ "ssh100", "ssh100_Direct01", "ssh_sky", { "Stage/ssh100", "Stage/Common/cmn017", "Stage/Common/cmn018" } },
{ "ssh101", "ssh101_Direct01", "ssh_sky", { "Stage/ssh101" } },
{ "ssh200", "ssh200_Direct01", "ssh_sky", { "Stage/Common/cmn017", "Stage/Common/cmn018", "Stage/Common/cmn019", "Stage/ssh200" } },
{ "ssh201", "ssh200_Direct01", "ssh_sky", { "Stage/ssh201" } },
{ "ssh205", "ssh200_Direct01", "ssh_sky", { "Stage/Common/cmn017", "Stage/Common/cmn019", "Stage/ssh205" } },
{ "ActD_Africa", "Direct01", "afr_sky_day", { "Stage/ActD_Africa", "Stage/Common/cmn020" } },
{ "ActD_Beach", "light", "sea_sky_day", { "Stage/ActD_Beach", "Stage/Common/cmn021", "Stage/Common/cmn022", "Stage/Common/cmn023" } },
{ "ActD_China", "Direct01", "chn_sky_day", { "Stage/ActD_China", "Stage/Common/cmn024", "Stage/Common/cmn025", "Stage/Common/cmn026" } },
{ "ActD_EU", "Direct01", "euc_sky_day", { "Stage/ActD_EU", "Stage/Common/cmn027", "Stage/Common/cmn028", "Stage/Common/cmn029", "Stage/Common/cmn030", "Stage/Common/cmn031", "Stage/Common/cmn032", "Stage/Common/cmn033", "Stage/Common/cmn034" } },
{ "ActD_MykonosAct1", "light", "myk_sky_morning", { "Stage/ActD_MykonosAct1", "Stage/Common/cmn035", "Stage/Common/cmn036", "Stage/Common/cmn037", "Stage/Common/cmn038" } },
{ "ActD_MykonosAct2", "light", "myk_sky_day", { "Stage/Common/cmn035", "Stage/Common/cmn036", "Stage/ActD_MykonosAct2", "Stage/Common/cmn039" } },
{ "ActD_NY", "FDirect01", "nyc_sky_day", { "Stage/ActD_NY", "Stage/Common/cmn040", "Stage/Common/cmn041" } },
{ "ActD_Petra", "light", "ptr_sky_day", { "Stage/ActD_Petra", "Stage/Common/cmn042", "Stage/Common/cmn043", "Stage/Common/cmn044", "Stage/Common/cmn045", "Stage/Common/cmn046", "Stage/Common/cmn047" } },
{ "ActD_Snow", "light", "snw_sky_day", { "Stage/ActD_Snow", "Stage/Common/cmn048" } },
{ "ActD_SubAfrica_01", "Direct01", "sky", { "Stage/ActD_SubAfrica_01", "Stage/Common/cmn049" } },
{ "ActD_SubAfrica_03", "Light01", "afr_sky_02", { "Stage/ActD_SubAfrica_03" } },
{ "ActD_SubBeach_02", "light", "sea_sky_day", { "Stage/Common/cmn021", "Stage/Common/cmn022", "Stage/Common/cmn023", "Stage/ActD_SubBeach_02" } },
{ "ActD_SubBeach_04", "light", "sea_sky_day_sub04", { "Stage/Common/cmn022", "Stage/Common/cmn023", "Stage/ActD_SubBeach_04", "Stage/Common/cmn050" } },
{ "ActD_SubChina_03", "Direct01", "chn_sky_day", { "Stage/Common/cmn024", "Stage/Common/cmn025", "Stage/Common/cmn026", "Stage/ActD_SubChina_03" } },
{ "ActD_SubChina_04", "Direct01", "chn_sky_day", { "Stage/Common/cmn024", "Stage/Common/cmn025", "Stage/Common/cmn026", "Stage/ActD_SubChina_04" } },
{ "ActD_SubEU_01", "Direct01", "euc_sky_eveningCloud", { "Stage/ActD_SubEU_01" } },
{ "ActD_SubEU_02", "Direct01", "euc_sky_day", { "Stage/Common/cmn028", "Stage/Common/cmn029", "Stage/Common/cmn030", "Stage/Common/cmn031", "Stage/Common/cmn032", "Stage/Common/cmn033", "Stage/Common/cmn034", "Stage/ActD_SubEU_02", "Stage/Common/cmn051" } },
{ "ActD_SubMykonos_01", "light", "myk_sky_morning", { "Stage/Common/cmn035", "Stage/Common/cmn036", "Stage/Common/cmn038", "Stage/ActD_SubMykonos_01" } },
{ "ActD_SubNY_01", "FDirect01", "nyc_sky_day", { "Stage/Common/cmn040", "Stage/Common/cmn041", "Stage/ActD_SubNY_01" } },
{ "ActD_SubPetra_03", "light", "ptr_sky_day", { "Stage/Common/cmn042", "Stage/Common/cmn043", "Stage/Common/cmn044", "Stage/Common/cmn045", "Stage/Common/cmn046", "Stage/Common/cmn047", "Stage/ActD_SubPetra_03" } },
{ "ActD_SubSnow_01", "light", "snw_sky_day", { "Stage/Common/cmn048", "Stage/ActD_SubSnow_01" } },
{ "ActN_AfricaEvil", "FDirect01", "afr_sky_night_000", { "Stage/ActN_AfricaEvil", "Stage/Common/cmn052", "Stage/Common/cmn053" } },
{ "ActN_BeachEvil", "FDirect01", "sea_sky_night", { "Stage/Common/cmn023", "Stage/ActN_BeachEvil", "Stage/Common/cmn054" } },
{ "ActN_ChinaEvil", "FDirect01", "chn_sky_night", { "Stage/ActN_ChinaEvil", "Stage/Common/cmn055", "Stage/Common/cmn056" } },
{ "ActN_EUEvil", "euc_night_Direct01", "euc_sky_night", { "Stage/Common/cmn029", "Stage/Common/cmn031", "Stage/ActN_EUEvil", "Stage/Common/cmn057" } },
{ "ActN_MykonosEvil", "Direct01", "evl_myk_sky_01", { "Stage/ActN_MykonosEvil", "Stage/Common/cmn058", "Stage/Common/cmn059" } },
{ "ActN_NYEvil", "FDirect01", "nyc_sky_night2", { "Stage/ActN_NYEvil", "Stage/Common/cmn060", "Stage/Common/cmn061", "Stage/Common/cmn062" } },
{ "ActN_PetraEvil", "Direct01", "ptr_sky_night", { "Stage/Common/cmn043", "Stage/Common/cmn045", "Stage/ActN_PetraEvil", "Stage/Common/cmn063", "Stage/Common/cmn064", "Stage/Common/cmn065", "Stage/Common/cmn066", "Stage/Common/cmn067", "Stage/Common/cmn068" } },
{ "ActN_SnowEvil", "light", "snw_sky_night", { "Stage/ActN_SnowEvil", "Stage/Common/cmn069", "Stage/Common/cmn070", "Stage/Common/cmn071" } },
{ "ActN_SubAfrica_01", "FDirect01", "afr_sky_night_000", { "Stage/Common/cmn052", "Stage/Common/cmn053", "Stage/ActN_SubAfrica_01" } },
{ "ActN_SubBeach_01", "euc_night_Direct01", "sea_sky_night", { "Stage/Common/cmn054", "Stage/ActN_SubBeach_01", "Stage/Common/cmn072", "Stage/Common/cmn073" } },
{ "ActN_SubChina_01", "FDirect01", "chn_sky_night", { "Stage/Common/cmn056", "Stage/ActN_SubChina_01", "Stage/Common/cmn074", "Stage/Common/cmn075" } },
{ "ActN_SubMykonos_01", "Direct01", "evl_myk_sky_01", { "Stage/Common/cmn058", "Stage/Common/cmn059", "Stage/ActN_SubMykonos_01" } },
{ "Act_EggmanLand", "Direct02_001", "egb_sky_day", { "Stage/Common/cmn029", "Stage/Common/cmn032", "Stage/Act_EggmanLand", "Stage/Common/cmn076" } },
{ "BossDarkGaia1_1Run", "Direct01", "fnl_sky_day", { "Stage/Common/cmn077", "Stage/BossDarkGaia1_1Run" } },
{ "BossDarkGaia1_2Run", "light", "fnl_sky_day", { "Stage/Common/cmn077", "Stage/BossDarkGaia1_2Run" } },
{ "BossDarkGaia1_3Run", "Direct01", "fnl_sky_day", { "Stage/Common/cmn077", "Stage/BossDarkGaia1_3Run" } },
{ "BossDarkGaiaMoray", "Direct01", "snw_sky_night", { "Stage/Common/cmn069", "Stage/Common/cmn070", "Stage/Common/cmn071", "Stage/BossDarkGaiaMoray" } },
{ "BossEggBeetle", "Direct01", "afrboss_sky_day", { "Stage/Common/cmn049", "Stage/BossEggBeetle" } },
{ "BossEggLancer", "FDirect01", "sea_sky_day", { "Stage/Common/cmn012", "Stage/Common/cmn022", "Stage/Common/cmn023", "Stage/Common/cmn032", "Stage/Common/cmn033", "Stage/BossEggLancer" } },
{ "BossEggRayBird", "FDirect01", "eucboss_sky_day", { "Stage/Common/cmn011", "Stage/Common/cmn012", "Stage/Common/cmn029", "Stage/Common/cmn030", "Stage/Common/cmn031", "Stage/Common/cmn032", "Stage/Common/cmn033", "Stage/Common/cmn051", "Stage/BossEggRayBird" } },
{ "BossPetra", "Direct01", "ptrboss_sky_night", { "Stage/Common/cmn043", "Stage/Common/cmn064", "Stage/Common/cmn065", "Stage/Common/cmn067", "Stage/BossPetra" } },
{ "BossPhoenix", "Direct01", "chn_sky_night", { "Stage/Common/cmn056", "Stage/BossPhoenix" } },
{ "Town_Africa", "twn_afr_day_light", "afr_sky_day", { "Stage/Common/cmn020", "Stage/Town_Africa", "Stage/Common/cmn078" } },
{ "Town_AfricaETF", "etf_afr_day_light", "afr_sky_day", { "Stage/Common/cmn020", "Stage/Common/cmn078", "Stage/Town_AfricaETF" } },
{ "Town_AfricaETF_Night", "etf_afr_night_light", "afr_sky_night", { "Stage/Common/cmn053", "Stage/Town_AfricaETF_Night", "Stage/Common/cmn079" } },
{ "Town_Africa_Night", "twn_afr_night_light", "afr_sky_night", { "Stage/Common/cmn053", "Stage/Common/cmn079", "Stage/Town_Africa_Night" } },
{ "Town_China", "twn_chn_day_light", "chn_sky_day", { "Stage/Common/cmn025", "Stage/Town_China" } },
{ "Town_ChinaETF", "etf_chn_day_light", "chn_sky_day", { "Stage/Common/cmn025", "Stage/Common/cmn026", "Stage/Town_ChinaETF" } },
{ "Town_ChinaETF_Night", "etf_chn_night_light", "chn_sky_night", { "Stage/Common/cmn056", "Stage/Common/cmn074", "Stage/Town_ChinaETF_Night" } },
{ "Town_China_Night", "twn_chn_night_light", "chn_sky_night", { "Stage/Common/cmn055", "Stage/Common/cmn056", "Stage/Town_China_Night" } },
{ "Town_EggManBase", "twn_egb_day_light", "egb_sky_day", { "Stage/Common/cmn029", "Stage/Common/cmn032", "Stage/Common/cmn076", "Stage/Town_EggManBase" } },
{ "Town_EULabo", "euc_professorroom_day_light", "euc_sky_day", { "Stage/Common/cmn029", "Stage/Common/cmn030", "Stage/Common/cmn031", "Stage/Common/cmn032", "Stage/Common/cmn033", "Stage/Common/cmn034", "Stage/Town_EULabo", "Stage/Common/cmn080" } },
{ "Town_EULabo_Night", "euc_professorroom_night_light", "euc_sky_night", { "Stage/Common/cmn035", "Stage/Common/cmn036", "Stage/Town_EULabo_Night", "Stage/Common/cmn081" } },
{ "Town_EuropeanCity", "twn_euc_day_light", "euc_sky_village_day", { "Stage/Common/cmn029", "Stage/Common/cmn030", "Stage/Common/cmn031", "Stage/Common/cmn032", "Stage/Common/cmn033", "Stage/Common/cmn034", "Stage/Town_EuropeanCity", "Stage/Common/cmn082" } },
{ "Town_EuropeanCityETF", "etf_euc_day_light.light", "euc_sky_01", { "Stage/Common/cmn029", "Stage/Common/cmn030", "Stage/Common/cmn031", "Stage/Common/cmn032", "Stage/Common/cmn033", "Stage/Common/cmn034", "Stage/Common/cmn082", "Stage/Town_EuropeanCityETF" } },
{ "Town_EuropeanCityETF_Night", "etf_euc_night_light", "euc_sky_night", { "Stage/Common/cmn029", "Stage/Common/cmn031", "Stage/Common/cmn057", "Stage/Town_EuropeanCityETF_Night", "Stage/Common/cmn083" } },
{ "Town_EuropeanCity_Night", "twn_euc_night_light", "euc_sky_night", { "Stage/Common/cmn029", "Stage/Common/cmn031", "Stage/Common/cmn057", "Stage/Common/cmn083", "Stage/Town_EuropeanCity_Night" } },
{ "Town_Mykonos", "twn_myk_day_light", "myk_sky_day", { "Stage/Common/cmn035", "Stage/Common/cmn036", "Stage/Common/cmn039", "Stage/Town_Mykonos" } },
{ "Town_MykonosETF", "light", "sky_day", { "Stage/Common/cmn035", "Stage/Common/cmn036", "Stage/Common/cmn039", "Stage/Town_MykonosETF" } },
{ "Town_MykonosETF_Night", "etf_myk_night_light", "evl_myk_sky_01", { "Stage/Common/cmn059", "Stage/Town_MykonosETF_Night", "Stage/Common/cmn084" } },
{ "Town_Mykonos_Night", "twn_myk_night_light", "myk_sky_night", { "Stage/Common/cmn059", "Stage/Common/cmn084", "Stage/Town_Mykonos_Night" } },
{ "Town_NYCity", "twn_nyc_day_light", "nyc_sky_day", { "Stage/Common/cmn041", "Stage/Town_NYCity", "Stage/Common/cmn085" } },
{ "Town_NYCityETF", "etf_nyc_day_light", "nyc_sky_day", { "Stage/Common/cmn041", "Stage/Common/cmn085", "Stage/Town_NYCityETF" } },
{ "Town_NYCityETF_Night", "twn_nyc_night_light", "nyc_sky_night", { "Stage/Common/cmn061", "Stage/Common/cmn062", "Stage/Town_NYCityETF_Night", "Stage/Common/cmn086" } },
{ "Town_NYCity_Night", "twn_nyc_night_light", "nyc_sky_night", { "Stage/Common/cmn061", "Stage/Common/cmn086", "Stage/Town_NYCity_Night" } },
{ "Town_PetraCapital", "twn_ptr_day_light", "ptr_sky_day", { "Stage/Town_PetraCapital", "Stage/Common/cmn087", "Stage/Common/cmn088" } },
{ "Town_PetraCapitalETF", "etf_ptr_day_light", "ptr_sky_day", { "Stage/Common/cmn087", "Stage/Common/cmn088", "Stage/Town_PetraCapitalETF" } },
{ "Town_PetraCapitalETF_Night", "etf_ptr_night_light", "ptr_village_sky_night", { "Stage/Common/cmn043", "Stage/Common/cmn045", "Stage/Common/cmn064", "Stage/Common/cmn066", "Stage/Town_PetraCapitalETF_Night", "Stage/Common/cmn089" } },
{ "Town_PetraCapital_Night", "twn_ptr_night_light", "ptr_village_sky_night", { "Stage/Common/cmn089", "Stage/Town_PetraCapital_Night" } },
{ "Town_PetraLabo", "labo_ptr_day_light", "ptr_sky_day", { "Stage/Common/cmn042", "Stage/Common/cmn043", "Stage/Common/cmn044", "Stage/Common/cmn045", "Stage/Common/cmn088", "Stage/Town_PetraLabo", "Stage/Common/cmn090" } },
{ "Town_PetraLabo_Night", "labo_ptr_night_light", "ptr_sky_night", { "Stage/Common/cmn043", "Stage/Common/cmn045", "Stage/Common/cmn063", "Stage/Common/cmn064", "Stage/Common/cmn065", "Stage/Common/cmn066", "Stage/Common/cmn089", "Stage/Town_PetraLabo_Night" } },
{ "Town_Snow", "twn_snw_day_light", "snw_sky_day", { "Stage/Common/cmn048", "Stage/Town_Snow" } },
{ "Town_SnowETF", "etf_snw_day_light", "snw_sky_day", { "Stage/Common/cmn048", "Stage/Town_SnowETF" } },
{ "Town_SnowETF_Night", "etf_snw_night_light", "snw_sky_night", { "Stage/Common/cmn069", "Stage/Common/cmn070", "Stage/Town_SnowETF_Night", "Stage/Common/cmn091" } },
{ "Town_Snow_Night", "twn_snw_night_light", "snw_sky_night", { "Stage/Common/cmn069", "Stage/Common/cmn070", "Stage/Common/cmn091", "Stage/Town_Snow_Night" } },
{ "Town_SouthEastAsia", "twn_sea_day_light", "sea_sky_day", { "Stage/Common/cmn021", "Stage/Common/cmn022", "Stage/Common/cmn023", "Stage/Town_SouthEastAsia" } },
{ "Town_SouthEastAsiaETF", "etf_sea_day_light", "sea_sky_day", { "Stage/Common/cmn021", "Stage/Common/cmn022", "Stage/Common/cmn023", "Stage/Town_SouthEastAsiaETF" } },
{ "Town_SouthEastAsiaETF_Night", "etf_sea_night_light", "sea_sky_night", { "Stage/Common/cmn054", "Stage/Common/cmn073", "Stage/Town_SouthEastAsiaETF_Night" } },
{ "Town_SouthEastAsia_Night", "twn_sea_night_light", "sea_sky_night", { "Stage/Common/cmn054", "Stage/Common/cmn073", "Stage/Town_SouthEastAsia_Night" } },
{ "ActD_SubMykonos_02", "light", "myk_sky_morning", { "Stage/Common/cmn035", "Stage/Common/cmn036", "Stage/Common/cmn037", "Stage/Common/cmn038", "Stage/ActD_SubMykonos_02" } },
{ "ActD_SubPetra_02", "light", "ptr_sky_day", { "Stage/Common/cmn043", "Stage/Common/cmn044", "Stage/Common/cmn045", "Stage/Common/cmn047", "Stage/Common/cmn090", "Stage/ActD_SubPetra_02" } },
{ "ActN_SubPetra_02", "Direct01", "ptr_sky_night", { "Stage/Common/cmn043", "Stage/Common/cmn045", "Stage/Common/cmn063", "Stage/Common/cmn064", "Stage/Common/cmn065", "Stage/Common/cmn066", "Stage/Common/cmn067", "Stage/Common/cmn068", "Stage/ActN_SubPetra_02" } },
{ "ActD_SubChina_01", "Direct01", "chn_sky_day", { "Stage/Common/cmn024", "Stage/Common/cmn025", "Stage/Common/cmn026", "Stage/ActD_SubChina_01" } },
{ "ActD_SubChina_02", "Direct01", "chn_sky_day", { "Stage/Common/cmn024", "Stage/Common/cmn025", "Stage/Common/cmn026", "Stage/ActD_SubChina_02" } },
{ "ActN_SubChina_02", "FDirect01", "chn_sky_night", { "Stage/Common/cmn056", "Stage/Common/cmn074", "Stage/Common/cmn075", "Stage/ActN_SubChina_02" } },
{ "ActD_SubBeach_01", "light", "sea_sky_day_sub01", { "Stage/Common/cmn022", "Stage/Common/cmn023", "Stage/ActD_SubBeach_01" } },
{ "ActD_SubBeach_03", "light", "sea_sky_day_sub04", { "Stage/Common/cmn022", "Stage/Common/cmn023", "Stage/Common/cmn050", "Stage/ActD_SubBeach_03" } },
{ "ActD_SubNY_02", "FDirect01", "nyc_sky_day", { "Stage/Common/cmn040", "Stage/Common/cmn041", "Stage/ActD_SubNY_02" } },
{ "ActN_SubNY_01", "FDirect01", "nyc_sky_night2", { "Stage/Common/cmn060", "Stage/Common/cmn061", "Stage/Common/cmn062", "Stage/ActN_SubNY_01" } },
{ "ActD_SubSnow_02", "light", "snw_sky_morning", { "Stage/ActD_SubSnow_02" } },
{ "ActD_SubSnow_03", "light", "snw_sky_day", { "Stage/Common/cmn048", "Stage/ActD_SubSnow_03" } },
{ "ActN_SubSnow_01", "light", "snw_sky_sub01_night", { "Stage/Common/cmn070", "Stage/Common/cmn071", "Stage/ActN_SubSnow_01" } },
{ "ActN_SubSnow_02", "light", "snw_sky_night", { "Stage/Common/cmn070", "Stage/Common/cmn071", "Stage/ActN_SubSnow_02" } },
{ "ActD_SubAfrica_02", "Direct01", "afr_sky_day", { "Stage/Common/cmn020", "Stage/Common/cmn078", "Stage/ActD_SubAfrica_02" } },
{ "ActN_SubAfrica_03", "FDirect01", "afr_sky_night_000", { "Stage/Common/cmn052", "Stage/Common/cmn053", "Stage/ActN_SubAfrica_03" } },
{ "ActD_SubEU_03", "Direct01", "euc_sky_evening", { "Stage/Common/cmn013", "Stage/ActD_SubEU_03" } },
{ "ActD_SubEU_04", "Direct01", "euc_sky_day", { "Stage/Common/cmn027", "Stage/Common/cmn029", "Stage/Common/cmn030", "Stage/Common/cmn031", "Stage/Common/cmn032", "Stage/Common/cmn033", "Stage/Common/cmn034", "Stage/Common/cmn080", "Stage/ActD_SubEU_04" } },
{ "ActN_SubEU_01", "euc_night_Direct01", "euc_evl_sky_000", { "Stage/Common/cmn036", "Stage/Common/cmn072", "Stage/Common/cmn081", "Stage/ActN_SubEU_01" } },
