#pragma once

enum DebugView
{
    DEBUG_VIEW_NONE,
    DEBUG_VIEW_DIFFUSE,
    DEBUG_VIEW_SPECULAR,
    DEBUG_VIEW_NORMAL,
    DEBUG_VIEW_FALLOFF,
    DEBUG_VIEW_EMISSION,
    DEBUG_VIEW_SHADOW,
    DEBUG_VIEW_GI,
    DEBUG_VIEW_REFLECTION,
    DEBUG_VIEW_MAX
};