#pragma once

enum DebugView
{
    DEBUG_VIEW_NONE,
    DEBUG_VIEW_COLOR,
    DEBUG_VIEW_DEPTH,
    DEBUG_VIEW_MOTION_VECTORS,
    DEBUG_VIEW_DIFFUSE,
    DEBUG_VIEW_SPECULAR,
    DEBUG_VIEW_SPECULAR_TINT,
    DEBUG_VIEW_SPECULAR_ENVIRONMENT,
    DEBUG_VIEW_SPECULAR_GLOSS,
    DEBUG_VIEW_SPECULAR_LEVEL,
    DEBUG_VIEW_SPECULAR_FRESNEL,
    DEBUG_VIEW_NORMAL,
    DEBUG_VIEW_FALLOFF,
    DEBUG_VIEW_EMISSION,
    DEBUG_VIEW_TRANS_COLOR,
    DEBUG_VIEW_REFRACTION,
    DEBUG_VIEW_REFRACTION_OVERLAY,
    DEBUG_VIEW_REFRACTION_OFFSET,
    DEBUG_VIEW_GI,
    DEBUG_VIEW_REFLECTION,
    DEBUG_VIEW_DIFFUSE_ALBEDO,
    DEBUG_VIEW_SPECULAR_ALBEDO,
    DEBUG_VIEW_MAX
};