#ifndef MATERIAL_FLAGS_H_INCLUDED
#define MATERIAL_FLAGS_H_INCLUDED

#define MATERIAL_FLAG_ADDITIVE        (1 << 0)
#define MATERIAL_FLAG_CONST_TEX_COORD (1 << 1)
#define MATERIAL_FLAG_REFLECTION      (1 << 2)
#define MATERIAL_FLAG_DOUBLE_SIDED    (1 << 3)

#endif